name: Update Git Pages
on: [push]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["danny-326/blog"]
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.DISPATCH_TOKEN }} # optional, default is ${{ github.token }}
          repository: danny-326/blog # optional, default is ${{ github.repository }}
          event-type: source_updated
